CREATE TABLE [CARGOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [NOME] VARCHAR(150) NOT NULL,
    [DESCRICAO] VARCHAR(150) NULL,
    CONSTRAINT [PK_CARGOS] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [CLIENTES] (
    [ID] BIGINT NOT NULL IDENTITY,
    [Tipo] int NOT NULL,
    [NOME_COMPLETO_RAZAO_SOCIAL] VARCHAR(150) NOT NULL,
    [CPF_CNPJ] VARCHAR(150) NOT NULL,
    [RG_INSCRICAO_ESTADUAL] VARCHAR(150) NULL,
    [DATA_NASCIMENTO] DATETIME2 NULL,
    [LOGRADOURO] VARCHAR(125) NOT NULL,
    [LOGRADOURO_NUMERO] VARCHAR(125) NOT NULL,
    [COMPLEMENTO] VARCHAR(125) NULL,
    [REFERENCIA] VARCHAR(150) NULL,
    [CEP] VARCHAR(9) NOT NULL,
    [BAIRRO] VARCHAR(125) NOT NULL,
    [CIDADE] VARCHAR(125) NOT NULL,
    [UF] INT NOT NULL,
    [PAIS] VARCHAR(125) NULL,
    [TELEFONE] VARCHAR(125) NOT NULL,
    [TELEFONE_2] VARCHAR(125) NULL,
    [TELEFONE_3] VARCHAR(125) NULL,
    [EMAIL] VARCHAR(255) NULL,
    [CONVENIO_ATIVO] BIT NOT NULL,
    [CONVENIO_INATIVO] BIT NOT NULL,
    [CONVENIO_BLOQUEADO] BIT NOT NULL,
    [CONVENIO_LIMITE] DECIMAL(18,2) NULL,
    [CONVENIO_LIMITE_DISPONIVEL] DECIMAL(18,2) NULL,
    [CONVENIO_LIMITE_USADO)] DECIMAL(18,2) NULL,
    [CONVENIO__FECHAMENTO_VENCIMENTO] INT NOT NULL,
    CONSTRAINT [PK_CLIENTES] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [EMPRESAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [RAZAO_SOCIAL] VARCHAR(150) NOT NULL,
    [CodigoReferencia] nvarchar(max) NULL,
    [CNPJ] VARCHAR(150) NOT NULL,
    [INSCRICAO_ESTADUAL] VARCHAR(150) NOT NULL,
    [LOGRADOURO] VARCHAR(125) NOT NULL,
    [LOGRADOURO_NUMERO] VARCHAR(125) NOT NULL,
    [COMPLEMENTO] VARCHAR(125) NULL,
    [REFERENCIA] VARCHAR(150) NULL,
    [CEP] VARCHAR(9) NOT NULL,
    [BAIRRO] VARCHAR(125) NOT NULL,
    [CIDADE] VARCHAR(125) NOT NULL,
    [UF] INT NOT NULL,
    [PAIS] VARCHAR(125) NULL,
    [TELEFONE] VARCHAR(125) NOT NULL,
    [TELEFONE_2] VARCHAR(125) NULL,
    [TELEFONE_3] VARCHAR(125) NULL,
    [EMAIL] VARCHAR(255) NULL,
    CONSTRAINT [PK_EMPRESAS] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [FORNECEDORES] (
    [ID] BIGINT NOT NULL IDENTITY,
    [RAZAO_SOCIAL] VARCHAR(150) NOT NULL,
    [CNPJ] VARCHAR(150) NOT NULL,
    [INSCRICAO_ESTADUAL] VARCHAR(150) NOT NULL,
    [LOGRADOURO] VARCHAR(125) NOT NULL,
    [LOGRADOURO_NUMERO] VARCHAR(125) NOT NULL,
    [COMPLEMENTO] VARCHAR(125) NULL,
    [REFERENCIA] VARCHAR(150) NULL,
    [CEP] VARCHAR(9) NOT NULL,
    [BAIRRO] VARCHAR(125) NOT NULL,
    [CIDADE] VARCHAR(125) NOT NULL,
    [UF] INT NOT NULL,
    [PAIS] VARCHAR(125) NULL,
    [TELEFONE] VARCHAR(125) NOT NULL,
    [TELEFONE_2] VARCHAR(125) NULL,
    [TELEFONE_3] VARCHAR(125) NULL,
    [EMAIL] VARCHAR(255) NULL,
    CONSTRAINT [PK_FORNECEDORES] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [ITENS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CODIGO_BARRAS] VARCHAR(125) NOT NULL,
    [CODIGO_REFERENCIA] VARCHAR(125) NULL,
    [DESCRICAO] VARCHAR(125) NOT NULL,
    [DESCRICAO_PDV] VARCHAR(125) NULL,
    [CODIGO_AUXILIAR_BALANCA] VARCHAR(125) NULL,
    [GERAR_DADOS_AUXILIAR_BALANCA] BIT NOT NULL,
    [USAR_BALANCA_CHECKOUT] BIT NOT NULL,
    [CUSTO_REAL] DECIMAL(18,2) NULL,
    [MARGEM_LUCRO] DECIMAL(18,2) NULL,
    [PRECO_FINAL] DECIMAL(18,2) NOT NULL,
    [CUSTO_REAL_2] DECIMAL(18,2) NULL,
    [MARGEM_LUCRO_2] DECIMAL(18,2) NULL,
    [PRECO_FINAL_2] DECIMAL(18,2) NULL,
    [CUSTO_REAL_3] DECIMAL(18,2) NULL,
    [MARGEM_LUCRO_3] DECIMAL(18,2) NULL,
    [PRECO_FINAL_3] DECIMAL(18,2) NULL,
    [MULTIPLOS_PRECOS] BIT NOT NULL,
    [TIPO_ITEM] INT NOT NULL,
    [MODO_ITEM] INT NOT NULL,
    [UNIDADE_MEDIDA] INT NOT NULL,
    [ESTOQUE_ATUAL] INT NOT NULL,
    [ESTOQUE_MINIMO] INT NOT NULL,
    [GERENCIAR_ESTOQUE] BIT NOT NULL,
    [NOTIFICAR_ESTOQUE_BAIXO] BIT NOT NULL,
    [NCM] VARCHAR(125) NOT NULL,
    [CFOP] VARCHAR(125) NOT NULL,
    [TIPO_ICMS] BIGINT NOT NULL,
    [ICMS] VARCHAR(max) NOT NULL,
    [TIPO_PIS] BIGINT NOT NULL,
    [PIS] VARCHAR(max) NOT NULL,
    [TIPO_COFINS] BIGINT NOT NULL,
    [COFINS] VARCHAR(max) NOT NULL,
    CONSTRAINT [PK_ITENS] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [TRANSPORTADORAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CODIGO_REFERENCIA] VARCHAR(150) NULL,
    [RAZAO_SOCIAL] VARCHAR(150) NOT NULL,
    [CNPJ] VARCHAR(150) NOT NULL,
    [INSCRICAO_ESTADUAL] VARCHAR(150) NOT NULL,
    [LOGRADOURO] VARCHAR(125) NOT NULL,
    [LOGRADOURO_NUMERO] VARCHAR(125) NOT NULL,
    [COMPLEMENTO] VARCHAR(125) NULL,
    [REFERENCIA] VARCHAR(150) NULL,
    [CEP] VARCHAR(9) NOT NULL,
    [BAIRRO] VARCHAR(125) NOT NULL,
    [CIDADE] VARCHAR(125) NOT NULL,
    [UF] INT NOT NULL,
    [PAIS] VARCHAR(125) NULL,
    [TELEFONE] VARCHAR(125) NOT NULL,
    [TELEFONE_2] VARCHAR(125) NULL,
    [TELEFONE_3] VARCHAR(125) NULL,
    [EMAIL] VARCHAR(255) NULL,
    CONSTRAINT [PK_TRANSPORTADORAS] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [FUNCIONARIOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CARGO_ID] BIGINT NOT NULL,
    [NOME_COMPLETO] VARCHAR(150) NOT NULL,
    [CPF] VARCHAR(150) NOT NULL,
    [RG] VARCHAR(150) NULL,
    [DATA_NASCIMENTO] DATETIME2 NULL,
    [LOGRADOURO] VARCHAR(125) NOT NULL,
    [LOGRADOURO_NUMERO] VARCHAR(125) NOT NULL,
    [COMPLEMENTO] VARCHAR(125) NULL,
    [REFERENCIA] VARCHAR(150) NULL,
    [CEP] VARCHAR(9) NOT NULL,
    [BAIRRO] VARCHAR(125) NOT NULL,
    [CIDADE] VARCHAR(125) NOT NULL,
    [UF] INT NOT NULL,
    [PAIS] VARCHAR(125) NULL,
    [TELEFONE] VARCHAR(125) NOT NULL,
    [TELEFONE_2] VARCHAR(125) NULL,
    [TELEFONE_3] VARCHAR(125) NULL,
    [EMAIL] VARCHAR(255) NULL,
    CONSTRAINT [PK_FUNCIONARIOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_FUNCIONARIOS_CARGOS_CARGO_ID] FOREIGN KEY ([CARGO_ID]) REFERENCES [CARGOS] ([ID])
);
GO


CREATE TABLE [CLIENTES_FATURAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CLIENTE_ID] BIGINT NOT NULL,
    [DIA_FECHAMENTO_VENCIMENTO] INT NOT NULL,
    [MES_REFERENTE] INT NOT NULL,
    [ANO_REFERENTE] INT NOT NULL,
    [VALOR_FATURA] DECIMAL(18,2) NOT NULL,
    [PARCIALMENTE_PAGO] BIT NOT NULL,
    [PAGO] BIT NOT NULL,
    [VALOR_RESTANTE] DECIMAL(18,2) NOT NULL,
    [VALOR_PAGO] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_CLIENTES_FATURAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CLIENTES_FATURAS_CLIENTES_CLIENTE_ID] FOREIGN KEY ([CLIENTE_ID]) REFERENCES [CLIENTES] ([ID])
);
GO


CREATE TABLE [TERMINAIS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [EMPRESA_ID] BIGINT NOT NULL,
    [NOME] VARCHAR(150) NOT NULL,
    CONSTRAINT [PK_TERMINAIS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_TERMINAIS_EMPRESAS_EMPRESA_ID] FOREIGN KEY ([EMPRESA_ID]) REFERENCES [EMPRESAS] ([ID])
);
GO


CREATE TABLE [PEDIDOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [FuncionarioId] BIGINT NOT NULL,
    [VALOR_TOTAL] DECIMAL(18,2) NOT NULL,
    [VALOR_TOTAL_DESCONTO] DECIMAL(18,2) NULL,
    [VOLUME] DECIMAL(18,2) NOT NULL,
    [ABERTO_EM] DATETIME2 NOT NULL,
    [FINALIZADO_EM] DATETIME2 NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    CONSTRAINT [PK_PEDIDOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_PEDIDOS_FUNCIONARIOS_FuncionarioId] FOREIGN KEY ([FuncionarioId]) REFERENCES [FUNCIONARIOS] ([ID])
);
GO


CREATE TABLE [USUARIOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [FUNCIONARIO_ID] BIGINT NOT NULL,
    [NOME_USUARIO] VARCHAR(150) NOT NULL,
    [HASH_SENHA] VARCHAR(255) NOT NULL,
    [ATIVO] BIT NOT NULL,
    CONSTRAINT [PK_USUARIOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_USUARIOS_FUNCIONARIOS_FUNCIONARIO_ID] FOREIGN KEY ([FUNCIONARIO_ID]) REFERENCES [FUNCIONARIOS] ([ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [ENTRADAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [DATA_EMISSAO] DATETIME2 NOT NULL,
    [DATA_SAIDA] DATETIME2 NOT NULL,
    [DATA_ENTRADA] DATETIME2 NOT NULL,
    [TERMINAL_ID] BIGINT NOT NULL,
    [EMITENTE_ID] BIGINT NOT NULL,
    [TRANSPORTADORA_ID] BIGINT NOT NULL,
    [DESTINATARIO_ID] BIGINT NOT NULL,
    CONSTRAINT [PK_ENTRADAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_ENTRADAS_EMPRESAS_DESTINATARIO_ID] FOREIGN KEY ([DESTINATARIO_ID]) REFERENCES [EMPRESAS] ([ID]),
    CONSTRAINT [FK_ENTRADAS_FORNECEDORES_EMITENTE_ID] FOREIGN KEY ([EMITENTE_ID]) REFERENCES [FORNECEDORES] ([ID]),
    CONSTRAINT [FK_ENTRADAS_TERMINAIS_TERMINAL_ID] FOREIGN KEY ([TERMINAL_ID]) REFERENCES [TERMINAIS] ([ID]),
    CONSTRAINT [FK_ENTRADAS_TRANSPORTADORAS_TRANSPORTADORA_ID] FOREIGN KEY ([TRANSPORTADORA_ID]) REFERENCES [TRANSPORTADORAS] ([ID])
);
GO


CREATE TABLE [PEDIDOS_ITENS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [PEDIDO_ID] BIGINT NOT NULL,
    [ITEM_ID] BIGINT NOT NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    [VALOR_UNITARIO] DECIMAL(18,2) NOT NULL,
    [VALOR_UNITARIO_DESCONTO] DECIMAL(18,2) NULL,
    [QUANTIDADE] DECIMAL(18,3) NOT NULL,
    [VALOR_TOTAL] DECIMAL(18,2) NOT NULL,
    [VALOR_TOTAL_DESCONTO] DECIMAL(18,2) NULL,
    [DESCRICAO] VARCHAR(125) NOT NULL,
    [CODIGO_BARRAS] VARCHAR(125) NOT NULL,
    [CODIGO_REFERENCIA] VARCHAR(125) NULL,
    [UNIDADE_MEDIDA] INT NOT NULL,
    [TIPO_ITEM] INT NOT NULL,
    [NCM] VARCHAR(125) NOT NULL,
    [CFOP] VARCHAR(125) NOT NULL,
    [TIPO_ICMS] BIGINT NOT NULL,
    [ICMS] VARCHAR(max) NOT NULL,
    [TIPO_PIS] BIGINT NOT NULL,
    [PIS] VARCHAR(max) NOT NULL,
    [TIPO_COFINS] BIGINT NOT NULL,
    [COFINS] VARCHAR(max) NOT NULL,
    CONSTRAINT [PK_PEDIDOS_ITENS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_PEDIDOS_ITENS_ITENS_ITEM_ID] FOREIGN KEY ([ITEM_ID]) REFERENCES [ITENS] ([ID]),
    CONSTRAINT [FK_PEDIDOS_ITENS_PEDIDOS_PEDIDO_ID] FOREIGN KEY ([PEDIDO_ID]) REFERENCES [PEDIDOS] ([ID])
);
GO


CREATE TABLE [CAIXAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [USUARIO_ID] BIGINT NOT NULL,
    [TERMINAL_ID] BIGINT NOT NULL,
    [STATUS] INT NOT NULL,
    [ABERTO_EM] DATETIME2 NOT NULL,
    [FECHADO_EM] DATETIME2 NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    [MOTIVO_CANCELAMENTO] VARCHAR(125) NULL,
    [SALDO_INICIAL] DECIMAL(18,2) NOT NULL,
    [SALDO_SUPRIMENTO] DECIMAL(18,2) NOT NULL,
    [SALDO_FINAL] DECIMAL(18,2) NOT NULL,
    [SALDO_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [SALDO_CHEQUE] DECIMAL(18,2) NOT NULL,
    [SALDO_OUTROS] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_OUTROS] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_CHEQUE] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_CANCELADO_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_CANCELADO_CHEQUE] DECIMAL(18,2) NOT NULL,
    [SUPRIMENTO_CANCELADO_OUTROS] DECIMAL(18,2) NOT NULL,
    [ENTRADA_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CARTAO_CREDITO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CARTAO_DEBITO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CARTAO_CONVENIO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CARTAO_VOUCHER] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CHEQUE] DECIMAL(18,2) NOT NULL,
    [ENTRADA_OUTROS] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_CARTAO_CREDITO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_CARTAO_DEBITO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_CARTAO_CONVENIO] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_CARTAO_VOUCHER] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_CHEQUE] DECIMAL(18,2) NOT NULL,
    [ENTRADA_CANCELADA_OUTROS] DECIMAL(18,2) NOT NULL,
    [SAIDA_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [SAIDA_CHEQUE] DECIMAL(18,2) NOT NULL,
    [SAIDA_OUTROS] DECIMAL(18,2) NOT NULL,
    [SAIDA_CANCELADA_DINHEIRO] DECIMAL(18,2) NOT NULL,
    [SAIDA_CANCELADA_CHEQUE] DECIMAL(18,2) NOT NULL,
    [SAIDA_CANCELADA_OUTROS] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_CAIXAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CAIXAS_TERMINAIS_TERMINAL_ID] FOREIGN KEY ([TERMINAL_ID]) REFERENCES [TERMINAIS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_CAIXAS_USUARIOS_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [USUARIOS] ([ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [ENTRADAS_ITENS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [ENTRADA_ID] BIGINT NOT NULL,
    [PRODUTO_ID] BIGINT NOT NULL,
    [CODIGO_PRODUTO] VARCHAR(150) NOT NULL,
    [DESCRICAO] VARCHAR(150) NOT NULL,
    [UNIDADE_MEDIDA_ORIGEM] INT NOT NULL,
    [UNIDADE_MEDIDA_DESTINO] INT NOT NULL,
    [UNIDADE_MEDIDA_CONVERSAO] INT NOT NULL,
    [VALOR_UNITARIO] DECIMAL(18,2) NOT NULL,
    [QUANTIDADE] DECIMAL(18,3) NOT NULL,
    [VALOR_TOTAL] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_ENTRADAS_ITENS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_ENTRADAS_ITENS_ENTRADAS_ENTRADA_ID] FOREIGN KEY ([ENTRADA_ID]) REFERENCES [ENTRADAS] ([ID]),
    CONSTRAINT [FK_ENTRADAS_ITENS_ITENS_PRODUTO_ID] FOREIGN KEY ([PRODUTO_ID]) REFERENCES [ITENS] ([ID])
);
GO


CREATE TABLE [CAIXAS_ENTRADAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CAIXA_ID] BIGINT NOT NULL,
    [DATA_ENTRADA] DATETIME2 NOT NULL,
    [TIPO] INT NOT NULL,
    [VALOR] DECIMAL(18,2) NOT NULL,
    [CANCELADA_EM] DATETIME2 NULL,
    [FOI_CANCELADA] BIT NOT NULL,
    [MOTIVO_CANCELAMENTO] VARCHAR(150) NULL,
    CONSTRAINT [PK_CAIXAS_ENTRADAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CAIXAS_ENTRADAS_CAIXAS_CAIXA_ID] FOREIGN KEY ([CAIXA_ID]) REFERENCES [CAIXAS] ([ID])
);
GO


CREATE TABLE [CAIXAS_SAIDAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CAIXA_ID] BIGINT NOT NULL,
    [DATA_SAIDA] DATETIME2 NOT NULL,
    [TIPO] INT NOT NULL,
    [VALOR] DECIMAL(18,2) NOT NULL,
    [FOI_CANCELADA] BIT NOT NULL,
    [CANCELADA_EM] DATETIME2 NULL,
    [MOTIVO_CANCELAMENTO] VARCHAR(150) NULL,
    CONSTRAINT [PK_CAIXAS_SAIDAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CAIXAS_SAIDAS_CAIXAS_CAIXA_ID] FOREIGN KEY ([CAIXA_ID]) REFERENCES [CAIXAS] ([ID])
);
GO


CREATE TABLE [CAIXAS_SUPRIMENTOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CAIXA_ID] BIGINT NOT NULL,
    [TIPO] INT NOT NULL,
    [DATA_SUPRIMENTO] DATETIME2 NOT NULL,
    [VALOR] DECIMAL(18,2) NOT NULL,
    [FOI_CANCELADO] BIT NOT NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    [MOTIVO_CANCELAMENTO] VARCHAR(150) NULL,
    CONSTRAINT [PK_CAIXAS_SUPRIMENTOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CAIXAS_SUPRIMENTOS_CAIXAS_CAIXA_ID] FOREIGN KEY ([CAIXA_ID]) REFERENCES [CAIXAS] ([ID])
);
GO


CREATE TABLE [VENDAS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [CAIXA_ID] BIGINT NOT NULL,
    [VOLUME] BIGINT NOT NULL,
    [VALOR_TOTAL] DECIMAL(18,2) NOT NULL,
    [VALOR_TOTAL_DESCONTO] DECIMAL(18,2) NULL,
    [TROCO] DECIMAL(18,2) NOT NULL,
    [CPF_CNPJ_NOTA] VARCHAR(150) NULL,
    [ABERTA_EM] DATETIME2 NOT NULL,
    [FECHADA_EM] DATETIME2 NULL,
    [CANCELADA_EM] DATETIME2 NULL,
    [EM_ESPERA] BIT NOT NULL,
    [CFE_XML] VARCHAR(max) NULL,
    CONSTRAINT [PK_VENDAS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_VENDAS_CAIXAS_CAIXA_ID] FOREIGN KEY ([CAIXA_ID]) REFERENCES [CAIXAS] ([ID])
);
GO


CREATE TABLE [VENDAS_ITENS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [VENDA_ID] BIGINT NOT NULL,
    [ITEM_ID] BIGINT NOT NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    [DESCRICAO] VARCHAR(125) NOT NULL,
    [CODIGO_BARRAS] VARCHAR(125) NOT NULL,
    [CODIGO_REFERENCIA] VARCHAR(125) NULL,
    [UNIDADE_MEDIDA] INT NOT NULL,
    [TIPO_ITEM] INT NOT NULL,
    [NCM] VARCHAR(125) NOT NULL,
    [CFOP] VARCHAR(125) NOT NULL,
    [TIPO_ICMS] BIGINT NOT NULL,
    [ICMS] VARCHAR(max) NOT NULL,
    [TIPO_PIS] BIGINT NOT NULL,
    [PIS] VARCHAR(max) NOT NULL,
    [TIPO_COFINS] BIGINT NOT NULL,
    [COFINS] VARCHAR(max) NOT NULL,
    [VALOR_UNITARIO] DECIMAL(18,2) NOT NULL,
    [VALOR_UNITARIO_DESCONTO] DECIMAL(18,2) NULL,
    [QUANTIDADE] DECIMAL(18,3) NOT NULL,
    [VALOR_TOTAL] DECIMAL(18,2) NOT NULL,
    [VALOR_TOTAL_DESCONTO] DECIMAL(18,2) NULL,
    CONSTRAINT [PK_VENDAS_ITENS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_VENDAS_ITENS_ITENS_ITEM_ID] FOREIGN KEY ([ITEM_ID]) REFERENCES [ITENS] ([ID]),
    CONSTRAINT [FK_VENDAS_ITENS_VENDAS_VENDA_ID] FOREIGN KEY ([VENDA_ID]) REFERENCES [VENDAS] ([ID])
);
GO


CREATE TABLE [VENDAS_PAGAMENTOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [VENDA_ID] BIGINT NOT NULL,
    [CAIXA_ENTRADA_ID] BIGINT NOT NULL,
    [CANCELADO_EM] DATETIME2 NULL,
    [TIPO] INT NOT NULL,
    [VALOR_PAGO] DECIMAL(18,2) NOT NULL,
    [VALOR_PAGO_LIQUIDO] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_VENDAS_PAGAMENTOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_VENDAS_PAGAMENTOS_CAIXAS_ENTRADAS_CAIXA_ENTRADA_ID] FOREIGN KEY ([CAIXA_ENTRADA_ID]) REFERENCES [CAIXAS_ENTRADAS] ([ID]),
    CONSTRAINT [FK_VENDAS_PAGAMENTOS_VENDAS_VENDA_ID] FOREIGN KEY ([VENDA_ID]) REFERENCES [VENDAS] ([ID])
);
GO


CREATE TABLE [CLIENTES_LANCAMENTOS] (
    [ID] BIGINT NOT NULL IDENTITY,
    [FATURA_ID] BIGINT NOT NULL,
    [VENDA_PAGAMENTO_ID] BIGINT NOT NULL,
    [CRIADO_EM] DATETIME2 NOT NULL,
    [VALOR_LANCAMENTO] DECIMAL(18,2) NOT NULL,
    [PARCIALMENTE_PAGO] BIT NOT NULL,
    [PAGO] BIT NOT NULL,
    [VALOR_RESTANTE] DECIMAL(18,2) NOT NULL,
    [VALOR_PAGO] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_CLIENTES_LANCAMENTOS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CLIENTES_LANCAMENTOS_CLIENTES_FATURAS_FATURA_ID] FOREIGN KEY ([FATURA_ID]) REFERENCES [CLIENTES_FATURAS] ([ID]),
    CONSTRAINT [FK_CLIENTES_LANCAMENTOS_VENDAS_PAGAMENTOS_VENDA_PAGAMENTO_ID] FOREIGN KEY ([VENDA_PAGAMENTO_ID]) REFERENCES [VENDAS_PAGAMENTOS] ([ID])
);
GO


CREATE INDEX [IX_CAIXAS_TERMINAL_ID] ON [CAIXAS] ([TERMINAL_ID]);
GO


CREATE INDEX [IX_CAIXAS_USUARIO_ID] ON [CAIXAS] ([USUARIO_ID]);
GO


CREATE INDEX [IX_CAIXAS_ENTRADAS_CAIXA_ID] ON [CAIXAS_ENTRADAS] ([CAIXA_ID]);
GO


CREATE INDEX [IX_CAIXAS_SAIDAS_CAIXA_ID] ON [CAIXAS_SAIDAS] ([CAIXA_ID]);
GO


CREATE INDEX [IX_CAIXAS_SUPRIMENTOS_CAIXA_ID] ON [CAIXAS_SUPRIMENTOS] ([CAIXA_ID]);
GO


CREATE INDEX [IX_CLIENTES_FATURAS_CLIENTE_ID] ON [CLIENTES_FATURAS] ([CLIENTE_ID]);
GO


CREATE INDEX [IX_CLIENTES_LANCAMENTOS_FATURA_ID] ON [CLIENTES_LANCAMENTOS] ([FATURA_ID]);
GO


CREATE INDEX [IX_CLIENTES_LANCAMENTOS_VENDA_PAGAMENTO_ID] ON [CLIENTES_LANCAMENTOS] ([VENDA_PAGAMENTO_ID]);
GO


CREATE INDEX [IX_ENTRADAS_DESTINATARIO_ID] ON [ENTRADAS] ([DESTINATARIO_ID]);
GO


CREATE INDEX [IX_ENTRADAS_EMITENTE_ID] ON [ENTRADAS] ([EMITENTE_ID]);
GO


CREATE INDEX [IX_ENTRADAS_TERMINAL_ID] ON [ENTRADAS] ([TERMINAL_ID]);
GO


CREATE INDEX [IX_ENTRADAS_TRANSPORTADORA_ID] ON [ENTRADAS] ([TRANSPORTADORA_ID]);
GO


CREATE INDEX [IX_ENTRADAS_ITENS_ENTRADA_ID] ON [ENTRADAS_ITENS] ([ENTRADA_ID]);
GO


CREATE INDEX [IX_ENTRADAS_ITENS_PRODUTO_ID] ON [ENTRADAS_ITENS] ([PRODUTO_ID]);
GO


CREATE INDEX [IX_FUNCIONARIOS_CARGO_ID] ON [FUNCIONARIOS] ([CARGO_ID]);
GO


CREATE INDEX [IX_PEDIDOS_FuncionarioId] ON [PEDIDOS] ([FuncionarioId]);
GO


CREATE INDEX [IX_PEDIDOS_ITENS_ITEM_ID] ON [PEDIDOS_ITENS] ([ITEM_ID]);
GO


CREATE INDEX [IX_PEDIDOS_ITENS_PEDIDO_ID] ON [PEDIDOS_ITENS] ([PEDIDO_ID]);
GO


CREATE INDEX [IX_TERMINAIS_EMPRESA_ID] ON [TERMINAIS] ([EMPRESA_ID]);
GO


CREATE UNIQUE INDEX [IX_USUARIOS_FUNCIONARIO_ID] ON [USUARIOS] ([FUNCIONARIO_ID]);
GO


CREATE INDEX [IX_VENDAS_CAIXA_ID] ON [VENDAS] ([CAIXA_ID]);
GO


CREATE INDEX [IX_VENDAS_ITENS_ITEM_ID] ON [VENDAS_ITENS] ([ITEM_ID]);
GO


CREATE INDEX [IX_VENDAS_ITENS_VENDA_ID] ON [VENDAS_ITENS] ([VENDA_ID]);
GO


CREATE UNIQUE INDEX [IX_VENDAS_PAGAMENTOS_CAIXA_ENTRADA_ID] ON [VENDAS_PAGAMENTOS] ([CAIXA_ENTRADA_ID]);
GO


CREATE INDEX [IX_VENDAS_PAGAMENTOS_VENDA_ID] ON [VENDAS_PAGAMENTOS] ([VENDA_ID]);
GO


